<h2 style="color:green" align="center">Machine Learning With Python: Save And Load Trained Model</h2>

In [2]:
import pandas as pd
import numpy as np
from sklearn import linear_model

In [3]:
df = pd.read_csv("homeprices.csv")
df.head()

area   price
0  2600  550000
1  3000  565000
2  3200  610000
3  3600  680000
4  4000  725000

In [10]:
model = linear_model.LinearRegression()
model.fit(df[['area']],df.price)

LinearRegression()

In [11]:
model.coef_

array([135.78767123])

In [12]:
model.intercept_

180616.43835616432

In [13]:
model.score(df[['area']],df.price)

0.9584301138199486

In [14]:
model.predict([[5000]])

array([859554.79452055])

<h3 style='color:purple'>Save Model To a File Using Python Pickle</h3>

In [15]:
import pickle  # .pickle extension model , h5. or .json,  games or programs.exe

In [16]:
with open('model_pickle','wb') as file: # write binary 
    pickle.dump(model,file) # put model into file

<h4 style='color:purple'>Load Saved Model</h4>

In [17]:
with open('model_pickle','rb') as file: # read binary 
    ourModel = pickle.load(file) # model is loaded into : ourModel  

In [18]:
ourModel.coef_

array([135.78767123])

In [19]:
ourModel.intercept_

180616.43835616432

In [20]:
ourModel.predict([[5000]])

array([859554.79452055])

<h3 style='color:purple'>Save Trained Model Using joblib</h3>

In [21]:
import joblib

In [22]:
joblib.dump(model, 'model_joblib') # model name 

['model_joblib']

<h4 style='color:purple'>Load Saved Model</h4>

In [23]:
mj = joblib.load('model_joblib')

In [24]:
mj.coef_

array([135.78767123])

In [25]:
mj.intercept_

180616.43835616432

In [26]:
mj.predict([[5000]])

array([859554.79452055])